language: android
android:
  components:
    - tools
    - platform-tools
    - tools

before_install:
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"

env:
  global:
    - ADB_INSTALL_TIMEOUT=8
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3